steps:
  # Build the image using the commit SHA as tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/flaskimage/flaskimage-repo/flaskimage:$COMMIT_SHA', '.']

  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/flaskimage/flaskimage-repo/flaskimage:$COMMIT_SHA']

  # Deploy to Cloud Run with revision suffix
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'flaskimage'
      - '--image'
      - 'us-central1-docker.pkg.dev/flaskimage/flaskimage-repo/flaskimage:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--revision-suffix'
      - '$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/flaskimage/flaskimage-repo/flaskimage:$COMMIT_SHA'
